import { useState, useRef, useEffect, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { 
  Camera, Mic, MicOff, Video, VideoOff, Square, ArrowLeft, 
  Loader2, Play, SkipForward, CheckCircle, ChevronRight, AlertCircle
} from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { VisionAnalyzer } from "@/lib/visionAnalysis";
import { AudioAnalyzer } from "@/lib/audioAnalysis";
import { SpeechRecognitionService, SpeechAnalyzer } from "@/lib/speechRecognition";
import { FusionAlgorithm } from "@/lib/fusionAlgorithm";
import type { RawMetrics, FusedMetrics } from "@/lib/fusionAlgorithm";
import HRInterviewSummary from "./HRInterviewSummary";

interface HRQuestion {
  question: string;
  category: string;
  role: string;
  experience: string;
  difficulty: string;
  source_type: string;
  ideal_answer: string;
  keywords: string[];
  improved_question: string;
}

interface HRQuestionResult {
  question: string;
  category: string;
  answer: string;
  evaluation: {
    contentScore: number;
    deliveryScore: number;
    overallScore: number;
    starBreakdown: { situation: number; task: number; action: number; result: number };
    strengths: string[];
    improvements: string[];
    feedback: string;
    quickTip: string;
  } | null;
  emotionHistory: string[];
  avgMetrics: {
    eyeContact: number;
    posture: number;
    bodyLanguage: number;
    facialExpression: number;
  };
}

const HRInterview = () => {
  const navigate = useNavigate();
  const { toast } = useToast();

  // Interview state
  const [questions, setQuestions] = useState<HRQuestion[]>([]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [interviewStarted, setInterviewStarted] = useState(false);
  const [results, setResults] = useState<HRQuestionResult[]>([]);
  const [showSummary, setShowSummary] = useState(false);
  const [totalDuration, setTotalDuration] = useState(0);

  // Recording state
  const videoRef = useRef<HTMLVideoElement>(null);
  const overlayCanvasRef = useRef<HTMLCanvasElement>(null);
  const [isRecording, setIsRecording] = useState(false);
  const [isCameraOn, setIsCameraOn] = useState(false);
  const [isMicOn, setIsMicOn] = useState(false);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const [recordingTime, setRecordingTime] = useState(0);
  const [modelsLoaded, setModelsLoaded] = useState(false);

  // Metrics state
  const [currentMetrics, setCurrentMetrics] = useState<FusedMetrics | null>(null);
  const [transcript, setTranscript] = useState("");
  const [interimTranscript, setInterimTranscript] = useState("");
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [currentFeedback, setCurrentFeedback] = useState<string | null>(null);
  const [aiVisionMetrics, setAiVisionMetrics] = useState<{
    detectedEmotion?: string;
    gestureType?: string;
    postureType?: string;
  } | null>(null);

  // Refs
  const visionAnalyzerRef = useRef<VisionAnalyzer | null>(null);
  const audioAnalyzerRef = useRef<AudioAnalyzer | null>(null);
  const speechRecognitionRef = useRef<SpeechRecognitionService | null>(null);
  const speechAnalyzerRef = useRef<SpeechAnalyzer>(new SpeechAnalyzer());
  const fusionAlgorithmRef = useRef<FusionAlgorithm>(new FusionAlgorithm());
  const animationFrameRef = useRef<number | null>(null);
  const metricsHistoryRef = useRef<FusedMetrics[]>([]);
  const emotionHistoryRef = useRef<string[]>([]);
  const aiAnalysisIntervalRef = useRef<NodeJS.Timeout | null>(null);
  const lastAiAnalysisRef = useRef<number>(0);
  const timerIntervalRef = useRef<NodeJS.Timeout | null>(null);
  const totalTimerRef = useRef<NodeJS.Timeout | null>(null);

  const transcriptRef = useRef("");
  const interimTranscriptRef = useRef("");

  // Load questions using Gemini 2.5 Pro
  useEffect(() => {
    const loadQuestions = async () => {
      setIsLoading(true);
      try {
        // Try Gemini 2.5 Pro first
        const { data, error } = await supabase.functions.invoke('gemini-generate-hr-questions', {
          body: {
            role: "Software Engineer",        // Change this dynamically later if needed
            experience_years: 3,
            count: 6,
            difficulty_preference: "mixed"
          }
        });

        if (!error && data?.questions && Array.isArray(data.questions) && data.questions.length >= 4) {
          setQuestions(data.questions);
          toast({ title: "✅ Questions generated by Gemini 2.5 Pro" });
          setIsLoading(false);
          return;
        }

        // Fallback to static JSON
        console.warn("Gemini failed, using static questions");
        const response = await fetch('/data/hr_interview_questions.json');
        const allQuestions: HRQuestion[] = await response.json();
        const selectedQuestions = selectDiverseQuestions(allQuestions, 6);
        setQuestions(selectedQuestions);
        toast({ title: "Using static questions (Gemini fallback)" });

      } catch (error) {
        console.error('Failed to load questions:', error);
        toast({ 
          title: "Error Loading Questions", 
          description: "Using fallback static questions", 
          variant: "destructive" 
        });

        // Last resort fallback
        try {
          const response = await fetch('/data/hr_interview_questions.json');
          const allQuestions: HRQuestion[] = await response.json();
          setQuestions(selectDiverseQuestions(allQuestions, 5));
        } catch {}
      } finally {
        setIsLoading(false);
      }
    };

    loadQuestions();
  }, [toast]);

  const selectDiverseQuestions = (allQuestions: HRQuestion[], count: number): HRQuestion[] => {
    // Your existing function (unchanged)
    const categories = [...new Set(allQuestions.map(q => q.category))];
    const selected: HRQuestion[] = [];
    const usedCategories = new Set<string>();

    for (const cat of categories) {
      if (selected.length >= count) break;
      const catQuestions = allQuestions.filter(q => q.category === cat);
      const randomQ = catQuestions[Math.floor(Math.random() * catQuestions.length)];
      if (randomQ && !usedCategories.has(cat)) {
        selected.push(randomQ);
        usedCategories.add(cat);
      }
    }

    while (selected.length < count) {
      const remaining = allQuestions.filter(q => !selected.includes(q));
      if (remaining.length === 0) break;
      const randomQ = remaining[Math.floor(Math.random() * remaining.length)];
      selected.push(randomQ);
    }
    return selected;
  };

  // Rest of your code remains exactly the same (only loadQuestions changed)
  // ... [All your existing code from initialize models to the end]

  // Initialize models (unchanged)
  useEffect(() => {
    const init = async () => {
      try {
        console.log("Initializing AI models for HR interview...");
        visionAnalyzerRef.current = new VisionAnalyzer();
        await visionAnalyzerRef.current.initialize();
        setModelsLoaded(true);

        const speechService = new SpeechRecognitionService();
        if (speechService.isSupported()) {
          speechRecognitionRef.current = speechService;
          speechService.onTranscript((text, isFinal) => {
            if (isFinal) {
              setTranscript(prev => prev + ' ' + text);
              setInterimTranscript('');
              transcriptRef.current = transcriptRef.current + ' ' + text;
            } else {
              setInterimTranscript(text);
              interimTranscriptRef.current = text;
            }
          });
        }
      } catch (error) {
        console.error("Model init error:", error);
        setModelsLoaded(true);
      }
    };
    init();

    fusionAlgorithmRef.current.setContext('job-seekers');

    return () => {
      if (visionAnalyzerRef.current) visionAnalyzerRef.current.cleanup();
      if (audioAnalyzerRef.current) audioAnalyzerRef.current.cleanup();
      if (speechRecognitionRef.current) speechRecognitionRef.current.stop();
      if (timerIntervalRef.current) clearInterval(timerIntervalRef.current);
      if (totalTimerRef.current) clearInterval(totalTimerRef.current);
      if (aiAnalysisIntervalRef.current) clearInterval(aiAnalysisIntervalRef.current);
    };
  }, []);

  // Fix for live transcript in AI analysis (important!)
  useEffect(() => { transcriptRef.current = transcript; }, [transcript]);
  useEffect(() => { interimTranscriptRef.current = interimTranscript; }, [interimTranscript]);

  // startRecording with live transcript fix (already included in your previous code)
  // ... keep your existing startRecording, stopRecording, evaluateAnswer, etc. exactly as you had

  // (For brevity, I kept the rest of your code unchanged — only loadQuestions + transcript refs updated)

  if (showSummary) {
    return (
      <HRInterviewSummary
        results={results}
        totalDuration={totalDuration}
        onRestart={() => window.location.reload()}
        onGoHome={() => navigate('/')}
      />
    );
  }

  // ... rest of your return JSX remains exactly the same
  // (I didn't change UI or logic except question loading)

  // [Paste your full existing return JSX here - it's unchanged]
};

export default HRInterview;
